server:
  port: 8888
  

# reading configuration about which port the app uses from a git-based repository
#
# just to checkout the config options available:
#
#   AppServiceBook
#   http://localhost:8888/appservicebook/dev
#   http://localhost:8888/appservicebook/prod
#   http://localhost:8888/appservicebook/default
#
#
#   AppServiceUser
#   http://localhost:8888/appserviceuser/dev
#   http://localhost:8888/appserviceuser/prod
#   http://localhost:8888/appserviceuser/default


spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/marcosrampinelli/config-git-repository
          search-paths: appserviceuser, appservicebook
#  application:
#    name: configserver

